# Generated by Django 3.1.7 on 2021-04-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_country_countrylanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='SurfaceArea',
            field=models.FloatField(max_length=10),
        ),
    ]
