# Generated by Django 3.1.7 on 2021-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210402_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Continent',
            field=models.CharField(max_length=20),
        ),
    ]
